# Generated by Django 3.1.1 on 2020-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Phone', models.CharField(max_length=10, unique=True)),
                ('Password', models.CharField(max_length=30, unique=True)),
                ('Address', models.CharField(max_length=100, unique=True)),
                ('DOB', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
    ]
