# Generated by Django 3.1.1 on 2020-12-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=10, unique=True)),
                ('Item', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
