# Generated by Django 3.1.1 on 2020-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_seeking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeking',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
