# Generated by Django 3.1.1 on 2020-12-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_helping_hphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Phone',
        ),
    ]
