# Generated by Django 3.1.1 on 2020-12-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_register_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeking',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
