# Generated by Django 3.1.1 on 2020-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_seeking_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeking',
            old_name='img',
            new_name='Img',
        ),
        migrations.AlterField(
            model_name='register',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
